name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: card.tex
          latexmk_use_xelatex: true
      - name: Upload PDF file
        uses: softprops/action-gh-release@v2
        if: startWith(github.ref, 'refs/tags/')
        with:
          name: PDF
          files: card.pdf
